# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :hostonly, "10.11.12.13"

  config.vm.share_folder("scripts", "/home/vagrant/scripts", "../../scripts", :nfs => true)
  config.vm.share_folder("php", "/usr/share/nginx/www/php", "../../src/main/php", :nfs => true)

  config.vm.forward_port 80, 8081

end
